### ISSUE TITLE
Bug in Occurrence Operator

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#176]
We're running into a bug with the occurrence operator when running with temp tables enabled.  The error occurs under PostgreSQL and Impala.

Here's the sample statement that causes the error when run against the OMOPv4 Plus formatted SynPUF 250 sample dataset:

```
-> cat /tmp/blah.json
[["occurrence",4,["union",["icd9","203","203.0","203.00","203.01","203.02",{"label":"icd9 mm"}],["icd10","C90.00","C90.01","C90.02",{"label":"icd10 mm"}],{"label":"mm dx"}],{"within":"90d","label":"4th mm dx"}]]
```

Here's the command I ran to recreate the error:

```
-> DOCKER_SCRATCH_DATABASE=jigsaw_temp CONCEPTQL_FORCE_TEMP_TABLES=true bundle exec ruby bin/conceptql run_statement /tmp/blah.json
SELECT * FROM (SELECT "person_id" AS "person_id", "condition_occurrence_id" AS "criterion_id", CAST('condition_occurrence' AS text) AS "criterion_table", CAST('condition_occurrence' AS text) AS "criterion_domain", CAST("condition_start_date" AS date) AS "start_date", CAST(coalesce("condition_end_date", "condition_start_date") AS date) AS "end_date", CAST("condition_source_value" AS text) AS "source_value", CAST("condition_source_vocabulary_id" AS text) AS "source_vocabulary_id" FROM "condition_occurrence" AS "tab" WHERE (("condition_source_value" IN ('203', '203.0', '203.00', '203.01', '203.02')) AND ("condition_source_vocabulary_id" = 2))) AS "t1";
SELECT * FROM (SELECT "person_id" AS "person_id", "condition_occurrence_id" AS "criterion_id", CAST('condition_occurrence' AS text) AS "criterion_table", CAST('condition_occurrence' AS text) AS "criterion_domain", CAST("condition_start_date" AS date) AS "start_date", CAST(coalesce("condition_end_date", "condition_start_date") AS date) AS "end_date", CAST("condition_source_value" AS text) AS "source_value", CAST("condition_source_vocabulary_id" AS text) AS "source_vocabulary_id" FROM "condition_occurrence" AS "tab" WHERE (("condition_source_value" IN ('C90.00', 'C90.01', 'C90.02')) AND ("condition_source_vocabulary_id" IN (34, 70)))) AS "t1";
SELECT * FROM (SELECT "person_id", "criterion_id", "criterion_table", "criterion_domain", "start_date", "end_date", "source_value", "source_vocabulary_id" FROM (SELECT * FROM (SELECT * FROM (SELECT "person_id", "criterion_id", "criterion_table", "criterion_domain", "start_date", "end_date", "source_value", "source_vocabulary_id" FROM "jigsaw_temp"."icd9_mm_6666_2_60e80e582b3af49bc264a05928ed3c50") AS "t1") AS "t1" UNION ALL (SELECT * FROM (SELECT * FROM (SELECT "person_id", "criterion_id", "criterion_table", "criterion_domain", "start_date", "end_date", "source_value", "source_vocabulary_id" FROM "jigsaw_temp"."icd10_mm_6666_3_fdad1e184f58eb926116d2884be75ac3") AS "t1") AS "t1")) AS "t1") AS "t1";
SELECT * FROM (WITH "#<Sequel::SQL::QualifiedIdentifier:0x0000000002cd8348>" AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY "person_id" ORDER BY "start_date", "criterion_id") AS "global_rn" FROM (SELECT "person_id", "criterion_id", "criterion_table", "criterion_domain", "start_date", "end_date", "source_value", "source_vocabulary_id" FROM "jigsaw_temp"."mm_dx_6666_4_9f61b0d9716bee4f93b75706292f18e0") AS "t1"), "#<Sequel::SQL::QualifiedIdentifier:0x0000000002cc83a8>" AS (SELECT "rest".*, "first"."global_rn" AS "initial_rn", ROW_NUMBER() OVER (PARTITION BY "first"."person_id", "first"."global_rn" ORDER BY "rest"."start_date" ASC, "rest"."criterion_id" ASC) AS "rn" FROM "jigsaw_temp"."occurrence_input_6666_5_47fd00c29fe614e502a8aa22548b6cc6" AS "first" INNER JOIN "jigsaw_temp"."occurrence_input_6666_5_47fd00c29fe614e502a8aa22548b6cc6" AS "rest" ON (("rest"."person_id" = "first"."person_id") AND ((("rest"."global_rn" > "first"."global_rn") AND ("rest"."start_date" <= CAST((CAST("first"."end_date" AS timestamp) + CAST('90 days ' AS interval)) AS date))) OR ("rest"."global_rn" = "first"."global_rn")))) SELECT "person_id", "criterion_id", "criterion_table", "criterion_domain", "start_date", "end_date", "source_value", "source_vocabulary_id" FROM "jigsaw_temp"."occurrence_joined_6666_6_40a9ce0bc7f03e32e78432f08c235204" WHERE ("rn" = 4) ORDER BY "global_rn") AS "t1";
SELECT * FROM (SELECT * FROM (SELECT "person_id", "criterion_id", "criterion_table", "criterion_domain", "start_date", "end_date", "source_value", "source_vocabulary_id" FROM "jigsaw_temp"."4th_mm_dx_6666_1_9693b4f6de93bbdbb952451e94a9130e") AS "t1") AS "t1"
[
  "occurrence",
  4,
  [
    "union",
    [
      "icd9",
      "203",
      "203.0",
      "203.00",
      "203.01",
      "203.02",
      {
        "label": "icd9 mm"
      }
    ],
    [
      "icd10",
      "C90.00",
      "C90.01",
      "C90.02",
      {
        "label": "icd10 mm"
      }
    ],
    {
      "label": "mm dx"
    }
  ],
  {
    "within": "90d",
    "label": "4th mm dx"
  }
]
/home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:146:in `async_exec': PG::UndefinedTable: ERROR:  relation "jigsaw_temp.occurrence_input_6666_7_9468acaefcea6f3fb1e2ad71f4cb2b53" does not exist (Sequel::DatabaseError)
LINE 1: ...ate" ASC, "rest"."criterion_id" ASC) AS "rn" FROM "jigsaw_te...
                                                             ^
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:146:in `block in execute_query'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/extensions/error_sql.rb:63:in `log_connection_yield'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:146:in `execute_query'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:134:in `block in execute'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:110:in `check_disconnect_errors'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:134:in `execute'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:478:in `_execute'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:296:in `block (2 levels) in execute'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:500:in `check_database_errors'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:296:in `block in execute'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/database/connecting.rb:264:in `block in synchronize'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/database/connecting.rb:264:in `synchronize'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:296:in `execute'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/database/query.rb:50:in `execute_dui'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/database/query.rb:43:in `execute_ddl'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/database/query.rb:76:in `run'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/database/schema_methods.rb:731:in `create_table_as'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/database/schema_methods.rb:183:in `create_table'
	from /home/ryan/jb/gems/conceptql/lib/conceptql/scope.rb:275:in `block (4 levels) in with_ctes'
	from /home/ryan/jb/gems/conceptql/lib/conceptql/scope.rb:273:in `each'
	from /home/ryan/jb/gems/conceptql/lib/conceptql/scope.rb:273:in `block (3 levels) in with_ctes'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/dataset/actions.rb:51:in `block in all'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/dataset/actions.rb:999:in `_all'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/dataset/actions.rb:51:in `all'
	from /home/ryan/jb/gems/conceptql/lib/conceptql/cli.rb:45:in `run_statement'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/ryan/.rvm/gems/ruby-2.4.2/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from bin/conceptql:5:in `<main>'
```

---
Moved from outcomesinsights/jigsaw#461
/cc @aguynamedryan

**Comment by aguynamedryan** [comment]
I've committed a new branch, issue_176, and it can be used to recreate and test the bug using the following command:

```
-> DOCKER_SCRATCH_DATABASE=jigsaw_temp CONCEPTQL_FORCE_TEMP_TABLES=true bundle exec ruby test/all_operations_test.rb results_for_issue_176
Run options: --seed 36697

# Running:

CREATE TABLE "jigsaw_temp"."4th_mm_dx_7496_1_aa7038f1a779ae7b9e62bac4653619a7" AS SELECT * FROM (WITH "#<Sequel::SQL::QualifiedIdentifier:0x0000000002ef7958>" AS (SELECT *, ROW_NUMBER() OVER (PARTITION BY "person_id" ORDER BY "start_date", "criterion_id") AS "global_rn" FROM (SELECT "person_id", "criterion_id", "criterion_table", "criterion_domain", "start_date", "end_date", "source_value", "source_vocabulary_id" FROM "jigsaw_temp"."mm_dx_7496_4_9a21c2ff72b18102c803d24346348978") AS "t1"), "#<Sequel::SQL::QualifiedIdentifier:0x0000000002eef988>" AS (SELECT "rest".*, "first"."global_rn" AS "initial_rn", ROW_NUMBER() OVER (PARTITION BY "first"."person_id", "first"."global_rn" ORDER BY "rest"."start_date" ASC, "rest"."criterion_id" ASC) AS "rn" FROM "jigsaw_temp"."occurrence_input_7496_5_d2243f52821f8fc1a7d32801a0f655bc" AS "first" INNER JOIN "jigsaw_temp"."occurrence_input_7496_5_d2243f52821f8fc1a7d32801a0f655bc" AS "rest" ON (("rest"."person_id" = "first"."person_id") AND ((("rest"."global_rn" > "first"."global_rn") AND ("rest"."start_date" <= CAST((CAST("first"."end_date" AS timestamp) + CAST('90 days ' AS interval)) AS date))) OR ("rest"."global_rn" = "first"."global_rn")))) SELECT "person_id", "criterion_id", "criterion_table", "criterion_domain", "start_date", "end_date", "source_value", "source_vocabulary_id" FROM "jigsaw_temp"."occurrence_joined_7496_6_f222291644fc5edbe135e694cabde822" WHERE ("rn" = 4) ORDER BY "global_rn") AS "t1"
E

Finished in 0.461753s, 2.1657 runs/s, 0.0000 assertions/s.

  1) Error:
ConceptQL::Operators#test_0001_should produce correct results for occurrence/results_for_issue_176.json:
Sequel::DatabaseError: PG::UndefinedTable: ERROR:  relation "jigsaw_temp.occurrence_input_7496_5_d2243f52821f8fc1a7d32801a0f655bc" does not exist
LINE 1: ...ate" ASC, "rest"."criterion_id" ASC) AS "rn" FROM "jigsaw_te...
                                                             ^

    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:146:in `async_exec'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:146:in `block in execute_query'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/extensions/error_sql.rb:63:in `log_connection_yield'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:146:in `execute_query'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:134:in `block in execute'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:110:in `check_disconnect_errors'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:134:in `execute'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:478:in `_execute'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:296:in `block (2 levels) in execute'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:500:in `check_database_errors'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:296:in `block in execute'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/database/connecting.rb:264:in `block in synchronize'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/database/connecting.rb:264:in `synchronize'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:296:in `execute'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/database/query.rb:50:in `execute_dui'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/database/query.rb:43:in `execute_ddl'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/database/query.rb:76:in `run'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/database/schema_methods.rb:731:in `create_table_as'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/database/schema_methods.rb:183:in `create_table'
    /home/ryan/jb/gems/conceptql/lib/conceptql/scope.rb:275:in `block (4 levels) in with_ctes'
    /home/ryan/jb/gems/conceptql/lib/conceptql/scope.rb:273:in `each'
    /home/ryan/jb/gems/conceptql/lib/conceptql/scope.rb:273:in `block (3 levels) in with_ctes'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/dataset/actions.rb:85:in `columns!'
    /home/ryan/.rvm/gems/ruby-2.4.2/gems/sequel-5.8.0/lib/sequel/dataset/actions.rb:75:in `columns'
    /home/ryan/jb/gems/conceptql/test/db_helper.rb:29:in `block in results'
    /home/ryan/jb/gems/conceptql/test/db_helper.rb:112:in `load_check'
    /home/ryan/jb/gems/conceptql/test/db_helper.rb:25:in `results'
    test/all_operations_test.rb:42:in `block (3 levels) in <main>'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by jenniferduryea** [comment]
This export built correctly and ran to completion.  Looks good!  Closing.
